In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
file_path = "D://DSML PRACTICAL//Datasets//House Data.csv"
df = pd.read_csv(file_path)

# Step 1: Clean the "price" column by removing non-numeric characters and converting to float
# df=df.loc[df["price"]!='34550000arrow_downward%3']
df["price"] = df["price"].str.replace("TL", "").str.replace(",", "").str.extract(r'(\d+)')[0].astype(float)
unique_values = df["price"].unique()



# Step 2: Clean the "GrossSquareMeters" column by removing "m2" and converting to float
df["GrossSquareMeters"] = df["GrossSquareMeters"].str.replace(" m2", "").astype(float)

# Step 3: Convert "BuildingAge" into numeric values
df["BuildingAge"] = df["BuildingAge"].replace({"21 Ve Üzeri": 21, "5-10": 7.5, "11-15": 13, "0 (Yeni)": 0,"16-20": 18, "20 Ve Üzeri":20}).astype(float)

# Handle missing values (fill with median for numeric columns)
df.fillna(df.mean(numeric_only=True), inplace=True)

In [2]:
df.columns

Index(['serial', 'district', 'price', 'address', 'AdUpdateDate', 'Category',
       'GrossSquareMeters', 'BuildingAge', 'NumberFloorsofBuilding',
       'UsingStatus', 'EligibilityForInvestment', 'BuildStatus', 'TitleStatus',
       'ItemStatus', 'NumberOfBathrooms', 'NumberOfWCs', 'AdCreationDate',
       'Type', 'NetSquareMeters', 'NumberOfRooms', 'FloorLocation',
       'HeatingType', 'CreditEligibility', 'InsideTheSite', 'StructureType',
       'MortgageStatus', 'Swap', 'Balcony', 'PriceStatus', 'RentalIncome',
       'NumberOfBalconies', 'BalconyType', 'HallSquareMeters',
       'WCSquareMeters', 'IsItVideoNavigable?', 'Subscription',
       'BathroomSquareMeters', 'BalconySquareMeters'],
      dtype='object')

In [3]:
summary_stats = df.groupby('BuildingAge')['price'].describe()

In [4]:
summary_stats

,count,mean,std,min,25%,50%,75%,max
BuildingAge,,,,,,,,
0.0,7333.0,2.716895e+06,5.959061e+06,20000.0,850000.0,1350000.0,2350000.0,2.730000e+08
1.0,798.0,3.001356e+06,5.774246e+06,99999.0,850000.0,1372500.0,3000000.0,1.100000e+08
2.0,963.0,4.596764e+06,5.648079e+07,285000.0,850000.0,1475000.0,2750000.0,1.750000e+09
3.0,1202.0,3.118105e+06,1.010505e+07,240000.0,826250.0,1450000.0,2650000.0,2.150000e+08
4.0,2199.0,3.418548e+06,1.711159e+07,200000.0,797250.0,1390000.0,3000000.0,7.390000e+08
7.5,5088.0,7.207567e+06,2.266947e+08,75000.0,803750.0,1400000.0,3200000.0,1.600000e+10
13.0,2220.0,7.094360e+06,5.694029e+07,35000.0,760000.0,1345000.0,3500000.0,2.000000e+09
18.0,783.0,5.711826e+06,4.588972e+07,85000.0,610000.0,1100000.0,3000000.0,1.250000e+09
20.0,1.0,9.250000e+05,NaN,925000.0,925000.0,925000.0,925000.0,9.250000e+05
21.0,4568.0,6.688592e+06,3.794103e+07,22222.0,685000.0,1300000.0,3100000.0,7.610000e+08